# Development docker file
# - Enables debugging
# - No SSL certificate generation
# - Rebuilds the static site every time the files change

services:
  frontend:
    build:
      context: frontend
      target: dev
    environment:
      - "BUNDLE_JS"
      - "URSUS_SITE_URL=https://localhost"
      - "GOOGLE_MAPS_JAVASCRIPT_API_KEY"
      - "GOOGLE_MAPS_PLACES_API_KEY"
      - "GOOGLE_TTS_API_KEY"
    volumes:
      - ".:/var/project:ro"
      - "./frontend/output:/var/output"
  backend:
    build:
      context: backend
      target: dev
      args:
        - "SSL_DOMAIN=localhost"
    environment:
      - "BUTTONDOWN_API_KEY"
    volumes:
      - "api_db:/var/db"
      - "api_staticfiles:/var/www/api/staticfiles"
      - "./backend/src:/srv/app"
  proxy:
    build: ./proxy
    environment:
      - "OPENEXCHANGERATES_API_KEY"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "backend"
    volumes:
      - "caddy_data:/data"
      - "caddy_config:/config"
      - "api_staticfiles:/var/www/api/staticfiles:ro"
      - "./frontend/output:/var/www/html"
      - "./frontend/content/redirects:/etc/caddy/redirects"
volumes:
  caddy_data:
  caddy_config:
  api_db:
  api_staticfiles: