people = [
    {
        "first_name": "José",
        "last_name": "González",
        "title": "",
        "local_address": {
            "street": "Friedrichstraße 123",
            "zusatz": "#1.5.6",
            "city": "Berlin",
            "post_code": "10115",
            "state": ["Berlin", "be"],
            "country": "Germany",
            "country_code": "DE",
        },
        "local_address_2": {
            "street": "Nordbahnstr. 456",
            "zusatz": "",
            "city": "Berlin",
            "post_code": "13131",
            "state": ["Berlin", "be"],
            "country": "Germany",
            "country_code": "DE",
        },
        "foreign_address": {
            "street": "456 Elm Street",
            "city": "New York",
            "country": "United States",
            "country_code": "US",
            "post_code": "10012",
        },
        "id_document": {
            "type": ["Passport", "RP"],
            "number": "AB1234567",
            "authority": "New York",
            "issue_date": "2020-12-31",
            "expiration_date": "2030-12-31",
        },
        "gender": "Male",
        "nationality": "Spain",
        "nationality_code": "ES",
        "birth_date": "1978-05-15",
        "birth_place": "València, Spain",
        "move_out_date": "2022-09-30",
        "birth_name": "Maria González",
        "religion": ["Roman Catholic Church", "Römisch-katholische Kirche"],
    },
    {
        "first_name": "Márk",
        "last_name": "Horváth",
        "title": "Prof.",
        "local_address": {
            "street": "Schönhauser Allee 67",
            "zusatz": "3. Stock rechts",
            "city": "Berlin",
            "post_code": "13120",
        },
        "id_document": {
            "type": ["Passport", "RP"],
            "number": "PL1234567",
            "authority": "Warsaw",
            "issue_date": "2021-10-01",
            "expiration_date": "2031-10-01",
        },
        "foreign_address": {
            "street": "987 Birch Rd",
            "city": "Budapest",
            "country": "Hungary",
            "country_code": "HU",
            "post_code": "1XYZ",
        },
        "gender": "Male",
        "nationality": "Hungary",
        "nationality_code": "HU",
        "birth_date": "1983-08-23",
        "birth_place": "Budapest, Hungary",
        "move_out_date": "2021-12-15",
        "birth_name": "Katalin Horváth",
        "religion": ["Other / No religion", "Sonstiges, nicht kirchensteuerpflichtig"],
    },
    {
        "first_name": "Sofia",
        "last_name": "Müller",
        "title": "Dr.",
        "local_address": {
            "street": "Kurfürstendamm 456",
            "zusatz": "",
            "city": "Berlin",
            "post_code": "12121",
        },
        "foreign_address": {
            "street": "Berliner Allee 23",
            "city": "Brandenburg",
            "country": "Germany",
            "country_code": "DE",
            "post_code": "23023",
        },
        "id_document": {
            "type": ["Personal ID", "PA"],
            "number": "D123456789",
            "authority": "Brandenburg",
            "issue_date": "2025-01-01",
            "expiration_date": "2030-01-01",
        },
        "gender": "Female",
        "nationality": "Germany",
        "nationality_code": "DE",
        "birth_date": "1990-02-10",
        "birth_place": "Munich, Germany",
        "move_out_date": "2023-04-05",
        "birth_name": "",
        "religion": ["Other / No religion", "Sonstiges, nicht kirchensteuerpflichtig"],
    },
    {
        "first_name": "Renata",
        "last_name": "Kowalczyk",
        "title": "Ms.",
        "local_address": {
            "street": "456 Unter den Linden",
            "city": "Berlin",
            "post_code": "23456",
        },
        "foreign_address": {
            "street": "ul. Warsawa 10",
            "city": "Kraków",
            "country": "Poland",
            "country_code": "PL",
            "post_code": "60-900",
        },
        "id_document": {
            "type": ["Passport", "RP"],
            "number": "PL1234567",
            "authority": "Warsaw",
            "issue_date": "2012-12-31",
            "expiration_date": "2032-12-31",
        },
        "gender": "Female",
        "nationality": "Poland",
        "nationality_code": "PL",
        "birth_date": "1988-12-03",
        "birth_place": "Kraków, Poland",
        "move_out_date": "2022-07-10",
        "birth_name": "",
        "religion": ["Other / No religion", "Sonstiges, nicht kirchensteuerpflichtig"],
    },
    {
        "first_name": "Élodie",
        "last_name": "Dubois",
        "title": "Ms.",
        "local_address": {
            "street": "Berliner Straße 101",
            "city": "Berlin",
            "post_code": "12021",
        },
        "foreign_address": {
            "street": "123 Rue du Château",
            "city": "Saint-Étienne-du-Rouvray",
            "country": "France",
            "country_code": "FR",
            "post_code": "12334",
        },
        "id_document": {
            "type": ["Passport", "RP"],
            "number": "FR1234567",
            "authority": "Paris",
            "issue_date": "2018-01-10",
            "expiration_date": "2028-12-31",
        },
        "gender": "Female",
        "nationality": "France",
        "nationality_code": "FR",
        "birth_date": "1987-03-20",
        "birth_place": "Paris, France",
        "move_out_date": "2022-08-30",
        "birth_name": "",
        "religion": ["Other / No religion", "Sonstiges, nicht kirchensteuerpflichtig"],
    },
]

companies = [
    {
        "name": "Musterfirma GmbH",
        "address": "Firmastraße 567",
        "city": "Berlin",
        "post_code": "10115",
        "state": ["Berlin", "be"],
    }
]
