export const countriesInEnglish = {
	AD: "Andorra",
	AE: "United Arab Emirates",
	AF: "Afghanistan",
	AG: "Antigua and Barbuda",
	AI: "Anguilla",
	AL: "Albania",
	AM: "Armenia",
	AO: "Angola",
	AQ: "Antarctica",
	AR: "Argentina",
	AS: "American Samoa",
	AT: "Austria",
	AU: "Australia",
	AW: "Aruba",
	AX: "Aland Islands",
	AZ: "Azerbaijan",
	BA: "Bosnia and Herzegovina",
	BB: "Barbados",
	BD: "Bangladesh",
	BE: "Belgium",
	BF: "Burkina Faso",
	BG: "Bulgaria",
	BH: "Bahrain",
	BI: "Burundi",
	BJ: "Benin",
	BL: "Saint Barthelemy",
	BM: "Bermuda",
	BN: "Brunei",
	BO: "Bolivia",
	BQ: "Bonaire, Saint Eustatius and Saba ",
	BR: "Brazil",
	BS: "Bahamas",
	BT: "Bhutan",
	BV: "Bouvet Island",
	BW: "Botswana",
	BY: "Belarus",
	BZ: "Belize",
	CA: "Canada",
	CC: "Cocos Islands",
	CD: "Democratic Republic of the Congo",
	CF: "Central African Republic",
	CG: "Republic of the Congo",
	CH: "Switzerland",
	CI: "Ivory Coast",
	CK: "Cook Islands",
	CL: "Chile",
	CM: "Cameroon",
	CN: "China",
	CO: "Colombia",
	CR: "Costa Rica",
	CU: "Cuba",
	CV: "Cape Verde",
	CW: "Curacao",
	CX: "Christmas Island",
	CY: "Cyprus",
	CZ: "Czech Republic",
	DE: "Germany",
	DJ: "Djibouti",
	DK: "Denmark",
	DM: "Dominica",
	DO: "Dominican Republic",
	DZ: "Algeria",
	EC: "Ecuador",
	EE: "Estonia",
	EG: "Egypt",
	EH: "Western Sahara",
	ER: "Eritrea",
	ES: "Spain",
	ET: "Ethiopia",
	FI: "Finland",
	FJ: "Fiji",
	FK: "Falkland Islands",
	FM: "Micronesia",
	FO: "Faroe Islands",
	FR: "France",
	GA: "Gabon",
	GB: "United Kingdom",
	GD: "Grenada",
	GE: "Georgia",
	GF: "French Guiana",
	GG: "Guernsey",
	GH: "Ghana",
	GI: "Gibraltar",
	GL: "Greenland",
	GM: "Gambia",
	GN: "Guinea",
	GP: "Guadeloupe",
	GQ: "Equatorial Guinea",
	GR: "Greece",
	GS: "South Georgia and the South Sandwich Islands",
	GT: "Guatemala",
	GU: "Guam",
	GW: "Guinea-Bissau",
	GY: "Guyana",
	HK: "Hong Kong",
	HM: "Heard Island and McDonald Islands",
	HN: "Honduras",
	HR: "Croatia",
	HT: "Haiti",
	HU: "Hungary",
	ID: "Indonesia",
	IE: "Ireland",
	IL: "Israel",
	IM: "Isle of Man",
	IN: "India",
	IO: "British Indian Ocean Territory",
	IQ: "Iraq",
	IR: "Iran",
	IS: "Iceland",
	IT: "Italy",
	JE: "Jersey",
	JM: "Jamaica",
	JO: "Jordan",
	JP: "Japan",
	KE: "Kenya",
	KG: "Kyrgyzstan",
	KH: "Cambodia",
	KI: "Kiribati",
	KM: "Comoros",
	KN: "Saint Kitts and Nevis",
	KP: "North Korea",
	KR: "South Korea",
	KW: "Kuwait",
	KY: "Cayman Islands",
	KZ: "Kazakhstan",
	LA: "Laos",
	LB: "Lebanon",
	LC: "Saint Lucia",
	LI: "Liechtenstein",
	LK: "Sri Lanka",
	LR: "Liberia",
	LS: "Lesotho",
	LT: "Lithuania",
	LU: "Luxembourg",
	LV: "Latvia",
	LY: "Libya",
	MA: "Morocco",
	MC: "Monaco",
	MD: "Moldova",
	ME: "Montenegro",
	MF: "Saint Martin",
	MG: "Madagascar",
	MH: "Marshall Islands",
	MK: "North Macedonia",
	ML: "Mali",
	MM: "Myanmar",
	MN: "Mongolia",
	MO: "Macao",
	MP: "Northern Mariana Islands",
	MQ: "Martinique",
	MR: "Mauritania",
	MS: "Montserrat",
	MT: "Malta",
	MU: "Mauritius",
	MV: "Maldives",
	MW: "Malawi",
	MX: "Mexico",
	MY: "Malaysia",
	MZ: "Mozambique",
	NA: "Namibia",
	NC: "New Caledonia",
	NE: "Niger",
	NF: "Norfolk Island",
	NG: "Nigeria",
	NI: "Nicaragua",
	NL: "Netherlands",
	NO: "Norway",
	NP: "Nepal",
	NR: "Nauru",
	NU: "Niue",
	NZ: "New Zealand",
	OM: "Oman",
	PA: "Panama",
	PE: "Peru",
	PF: "French Polynesia",
	PG: "Papua New Guinea",
	PH: "Philippines",
	PK: "Pakistan",
	PL: "Poland",
	PM: "Saint Pierre and Miquelon",
	PN: "Pitcairn",
	PR: "Puerto Rico",
	PS: "Palestinian Territory",
	PT: "Portugal",
	PW: "Palau",
	PY: "Paraguay",
	QA: "Qatar",
	RE: "Reunion",
	RO: "Romania",
	RS: "Serbia",
	RU: "Russia",
	RW: "Rwanda",
	SA: "Saudi Arabia",
	SB: "Solomon Islands",
	SC: "Seychelles",
	SD: "Sudan",
	SE: "Sweden",
	SG: "Singapore",
	SH: "Saint Helena",
	SI: "Slovenia",
	SJ: "Svalbard and Jan Mayen",
	SK: "Slovakia",
	SL: "Sierra Leone",
	SM: "San Marino",
	SN: "Senegal",
	SO: "Somalia",
	SR: "Suriname",
	SS: "South Sudan",
	ST: "Sao Tome and Principe",
	SV: "El Salvador",
	SX: "Sint Maarten",
	SY: "Syria",
	SZ: "Swaziland",
	TC: "Turks and Caicos Islands",
	TD: "Chad",
	TF: "French Southern Territories",
	TG: "Togo",
	TH: "Thailand",
	TJ: "Tajikistan",
	TK: "Tokelau",
	TL: "East Timor",
	TM: "Turkmenistan",
	TN: "Tunisia",
	TO: "Tonga",
	TR: "Turkey",
	TT: "Trinidad and Tobago",
	TV: "Tuvalu",
	TW: "Taiwan",
	TZ: "Tanzania",
	UA: "Ukraine",
	UG: "Uganda",
	UM: "United States Minor Outlying Islands",
	US: "United States",
	UY: "Uruguay",
	UZ: "Uzbekistan",
	VA: "Vatican",
	VC: "Saint Vincent and the Grenadines",
	VE: "Venezuela",
	VG: "British Virgin Islands",
	VI: "U.S. Virgin Islands",
	VN: "Vietnam",
	VU: "Vanuatu",
	WF: "Wallis and Futuna",
	WS: "Samoa",
	XK: "Kosovo",
	YE: "Yemen",
	YT: "Mayotte",
	ZA: "South Africa",
	ZM: "Zambia",
	ZW: "Zimbabwe",
};
export const countriesInGerman = {
	AD: "Andorra",
	AE: "Vereinigte Arabische Emirate",
	AF: "Afghanistan",
	AG: "Antigua und Barbuda",
	AI: "Anguilla",
	AL: "Albanien",
	AM: "Armenien",
	AO: "Angola",
	AQ: "Antarktis",
	AR: "Argentinien",
	AS: "Amerikanisch-Samoa",
	AT: "\u00d6sterreich",
	AU: "Australien",
	AW: "Aruba",
	AX: "\u00c5land",
	AZ: "Aserbaidschan",
	BA: "Bosnien und Herzegowina",
	BB: "Barbados",
	BD: "Bangladesch",
	BE: "Belgien",
	BF: "Burkina Faso",
	BG: "Bulgarien",
	BH: "Bahrain",
	BI: "Burundi",
	BJ: "Benin",
	BL: "Saint-Barth\u00e9lemy",
	BM: "Bermuda",
	BN: "Brunei",
	BO: "Bolivien",
	BQ: "Karibische Niederlande",
	BR: "Brasilien",
	BS: "Bahamas",
	BT: "Bhutan",
	BV: "Bouvetinsel",
	BW: "Botswana",
	BY: "Wei\u00dfrussland",
	BZ: "Belize",
	CA: "Kanada",
	CC: "Kokosinseln",
	CD: "Kongo (Dem. Rep.)",
	CF: "Zentralafrikanische Republik",
	CG: "Kongo",
	CH: "Schweiz",
	CI: "Elfenbeink\u00fcste",
	CK: "Cookinseln",
	CL: "Chile",
	CM: "Kamerun",
	CN: "China",
	CO: "Kolumbien",
	CR: "Costa Rica",
	CU: "Kuba",
	CV: "Kap Verde",
	CW: "Cura\u00e7ao",
	CX: "Weihnachtsinsel",
	CY: "Zypern",
	CZ: "Tschechien",
	DE: "Deutschland",
	DJ: "Dschibuti",
	DK: "D\u00e4nemark",
	DM: "Dominica",
	DO: "Dominikanische Republik",
	DZ: "Algerien",
	EC: "Ecuador",
	EE: "Estland",
	EG: "\u00c4gypten",
	EH: "Westsahara",
	ER: "Eritrea",
	ES: "Spanien",
	ET: "\u00c4thiopien",
	FI: "Finnland",
	FJ: "Fidschi",
	FK: "Falklandinseln",
	FM: "Mikronesien",
	FO: "F\u00e4r\u00f6er-Inseln",
	FR: "Frankreich",
	GA: "Gabun",
	GB: "Vereinigtes K\u00f6nigreich",
	GD: "Grenada",
	GE: "Georgien",
	GF: "Franz\u00f6sisch-Guayana",
	GG: "Guernsey",
	GH: "Ghana",
	GI: "Gibraltar",
	GL: "Gr\u00f6nland",
	GM: "Gambia",
	GN: "Guinea",
	GP: "Guadeloupe",
	GQ: "\u00c4quatorialguinea",
	GR: "Griechenland",
	GS: "S\u00fcdgeorgien und die S\u00fcdlichen Sandwichinseln",
	GT: "Guatemala",
	GU: "Guam",
	GW: "Guinea-Bissau",
	GY: "Guyana",
	HK: "Hongkong",
	HM: "Heard und die McDonaldinseln",
	HN: "Honduras",
	HR: "Kroatien",
	HT: "Haiti",
	HU: "Ungarn",
	ID: "Indonesien",
	IE: "Irland",
	IL: "Israel",
	IM: "Insel Man",
	IN: "Indien",
	IO: "Britisches Territorium im Indischen Ozean",
	IQ: "Irak",
	IR: "Iran",
	IS: "Island",
	IT: "Italien",
	JE: "Jersey",
	JM: "Jamaika",
	JO: "Jordanien",
	JP: "Japan",
	KE: "Kenia",
	KG: "Kirgisistan",
	KH: "Kambodscha",
	KI: "Kiribati",
	KM: "Komoren",
	KN: "St. Kitts und Nevis",
	KP: "Nordkorea",
	KR: "S\u00fcdkorea",
	KW: "Kuwait",
	KY: "Kaimaninseln",
	KZ: "Kasachstan",
	LA: "Laos",
	LB: "Libanon",
	LC: "St. Lucia",
	LI: "Liechtenstein",
	LK: "Sri Lanka",
	LR: "Liberia",
	LS: "Lesotho",
	LT: "Litauen",
	LU: "Luxemburg",
	LV: "Lettland",
	LY: "Libyen",
	MA: "Marokko",
	MC: "Monaco",
	MD: "Moldawien",
	ME: "Montenegro",
	MF: "Saint-Martin",
	MG: "Madagaskar",
	MH: "Marshallinseln",
	MK: "Nordmazedonien",
	ML: "Mali",
	MM: "Myanmar",
	MN: "Mongolei",
	MO: "Macao",
	MP: "N\u00f6rdliche Marianen",
	MQ: "Martinique",
	MR: "Mauretanien",
	MS: "Montserrat",
	MT: "Malta",
	MU: "Mauritius",
	MV: "Malediven",
	MW: "Malawi",
	MX: "Mexiko",
	MY: "Malaysia",
	MZ: "Mosambik",
	NA: "Namibia",
	NC: "Neukaledonien",
	NE: "Niger",
	NF: "Norfolkinsel",
	NG: "Nigeria",
	NI: "Nicaragua",
	NL: "Niederlande",
	NO: "Norwegen",
	NP: "Nepal",
	NR: "Nauru",
	NU: "Niue",
	NZ: "Neuseeland",
	OM: "Oman",
	PA: "Panama",
	PE: "Peru",
	PF: "Franz\u00f6sisch-Polynesien",
	PG: "Papua-Neuguinea",
	PH: "Philippinen",
	PK: "Pakistan",
	PL: "Polen",
	PM: "St. Pierre und Miquelon",
	PN: "Pitcairninseln",
	PR: "Puerto Rico",
	PS: "Pal\u00e4stina",
	PT: "Portugal",
	PW: "Palau",
	PY: "Paraguay",
	QA: "Katar",
	RE: "R\u00e9union",
	RO: "Rum\u00e4nien",
	RS: "Serbien",
	RU: "Russland",
	RW: "Ruanda",
	SA: "Saudi-Arabien",
	SB: "Salomonen",
	SC: "Seychellen",
	SD: "Sudan",
	SE: "Schweden",
	SG: "Singapur",
	SH: "St. Helena, Ascension und Tristan da Cunha",
	SI: "Slowenien",
	SJ: "Spitzbergen und Jan Mayen",
	SK: "Slowakei",
	SL: "Sierra Leone",
	SM: "San Marino",
	SN: "Senegal",
	SO: "Somalia",
	SR: "Suriname",
	SS: "S\u00fcdsudan",
	ST: "S\u00e3o Tom\u00e9 und Pr\u00edncipe",
	SV: "El Salvador",
	SX: "Sint Maarten",
	SY: "Syrien",
	SZ: "Swasiland",
	TC: "Turks-und Caicosinseln",
	TD: "Tschad",
	TF: "Franz\u00f6sische S\u00fcd- und Antarktisgebiete",
	TG: "Togo",
	TH: "Thailand",
	TJ: "Tadschikistan",
	TK: "Tokelau",
	TL: "Osttimor",
	TM: "Turkmenistan",
	TN: "Tunesien",
	TO: "Tonga",
	TR: "T\u00fcrkei",
	TT: "Trinidad und Tobago",
	TV: "Tuvalu",
	TW: "Taiwan",
	TZ: "Tansania",
	UA: "Ukraine",
	UG: "Uganda",
	UM: "Kleinere Inselbesitzungen der Vereinigten Staaten",
	US: "Vereinigte Staaten",
	UY: "Uruguay",
	UZ: "Usbekistan",
	VA: "Vatikanstadt",
	VC: "St. Vincent und die Grenadinen",
	VE: "Venezuela",
	VG: "Britische Jungferninseln",
	VI: "Amerikanische Jungferninseln",
	VN: "Vietnam",
	VU: "Vanuatu",
	WF: "Wallis und Futuna",
	WS: "Samoa",
	XK: "Kosovo",
	YE: "Jemen",
	YT: "Mayotte",
	ZA: "S\u00fcdafrika",
	ZM: "Sambia",
	ZW: "Simbabwe",
};
export const euCountries = new Set(['BE', 'BG', 'CZ', 'DK', 'DE', 'EE', 'IE', 'GR', 'ES', 'FR', 'HR', 'IT', 'CY', 'LV', 'LT', 'LU', 'HU', 'MT', 'NL', 'AT', 'PL', 'PT', 'RO', 'SI', 'SK', 'FI', 'SE']);
export const eeaCountries = new Set([...euCountries, ...['IS', 'LI', 'NO', 'CH']]);
